version: '3.8'

services:
  postgis:
    image: postgis/postgis:16-3.4
    container_name: svakenett-postgis
    environment:
      POSTGRES_DB: svakenett
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: weakgrid2024
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
